var miserables= {
   directed:false,
   graph:[

   ],
   nodes:[
      {
         nodeName:"#ubuntu-release"
      },
      {
         nodeName:"#ubuntu-unity"
      },
      {
         nodeName:"#ubuntu-x"
      },
      {
         nodeName:"#ubuntu-on-air"
      },
      {
         nodeName:"#xubuntu-devel"
      },
      {
         nodeName:"#ubuntu-phone"
      },
      {
         nodeName:"#ubuntu"
      },
      {
         nodeName:"#ubuntu-discuss"
      },
      {
         nodeName:"#xubuntu"
      },
      {
         nodeName:"#launchpad"
      },
      {
         nodeName:"#ubuntu-locoteams"
      },
      {
         nodeName:"#ubuntu-classroom"
      },
      {
         nodeName:"#ubuntu-devel"
      },
      {
         nodeName:"#ubuntu-bugs"
      },
      {
         nodeName:"#ubuntu-kernel"
      },
      {
         nodeName:"#ubuntu-beginners"
      },
      {
         nodeName:"#kubuntu"
      },
      {
         nodeName:"#ubuntu-uk"
      },
      {
         nodeName:"#ubuntu+1"
      },
      {
         nodeName:"#ubuntu-arm"
      },
      {
         nodeName:"#lubuntu"
      },
      {
         nodeName:"#ubuntu-motu"
      },
      {
         nodeName:"#kubuntu-devel"
      },
      {
         nodeName:"#ubuntu-community-team"
      },
      {
         nodeName:"#ubuntu-desktop"
      },
      {
         nodeName:"#ubuntu-meeting"
      },
      {
         nodeName:"#ubuntu-ops"
      },
      {
         nodeName:"#ubuntu-quality"
      },
      {
         nodeName:"#ubuntu-server"
      }
   ],
   links:[
      {
         source:0,
         target:1,
         value:12
      },
      {
         source:0,
         target:2,
         value:15
      },
      {
         source:0,
         target:3,
         value:5
      },
      {
         source:0,
         target:16,
         value:5
      },
      {
         source:0,
         target:5,
         value:8
      },
      {
         source:0,
         target:6,
         value:6
      },
      {
         source:0,
         target:22,
         value:13
      },
      {
         source:0,
         target:8,
         value:4
      },
      {
         source:0,
         target:9,
         value:25
      },
      {
         source:0,
         target:10,
         value:5
      },
      {
         source:0,
         target:11,
         value:19
      },
      {
         source:0,
         target:12,
         value:65
      },
      {
         source:0,
         target:13,
         value:26
      },
      {
         source:0,
         target:14,
         value:38
      },
      {
         source:0,
         target:15,
         value:6
      },
      {
         source:0,
         target:4,
         value:14
      },
      {
         source:0,
         target:17,
         value:8
      },
      {
         source:0,
         target:18,
         value:13
      },
      {
         source:0,
         target:19,
         value:28
      },
      {
         source:0,
         target:20,
         value:4
      },
      {
         source:0,
         target:21,
         value:29
      },
      {
         source:0,
         target:7,
         value:10
      },
      {
         source:0,
         target:23,
         value:14
      },
      {
         source:0,
         target:24,
         value:34
      },
      {
         source:0,
         target:25,
         value:56
      },
      {
         source:0,
         target:26,
         value:2
      },
      {
         source:0,
         target:27,
         value:30
      },
      {
         source:0,
         target:28,
         value:30
      },
      {
         source:1,
         target:2,
         value:12
      },
      {
         source:1,
         target:3,
         value:8
      },
      {
         source:1,
         target:16,
         value:4
      },
      {
         source:1,
         target:5,
         value:18
      },
      {
         source:1,
         target:6,
         value:39
      },
      {
         source:1,
         target:7,
         value:11
      },
      {
         source:1,
         target:8,
         value:2
      },
      {
         source:1,
         target:9,
         value:22
      },
      {
         source:1,
         target:10,
         value:6
      },
      {
         source:1,
         target:11,
         value:13
      },
      {
         source:1,
         target:12,
         value:51
      },
      {
         source:1,
         target:13,
         value:18
      },
      {
         source:1,
         target:14,
         value:17
      },
      {
         source:1,
         target:15,
         value:1
      },
      {
         source:1,
         target:4,
         value:2
      },
      {
         source:1,
         target:17,
         value:8
      },
      {
         source:1,
         target:18,
         value:15
      },
      {
         source:1,
         target:19,
         value:10
      },
      {
         source:1,
         target:20,
         value:4
      },
      {
         source:1,
         target:21,
         value:22
      },
      {
         source:1,
         target:22,
         value:10
      },
      {
         source:1,
         target:23,
         value:11
      },
      {
         source:1,
         target:24,
         value:49
      },
      {
         source:1,
         target:25,
         value:27
      },
      {
         source:1,
         target:26,
         value:2
      },
      {
         source:1,
         target:27,
         value:17
      },
      {
         source:1,
         target:28,
         value:14
      },
      {
         source:2,
         target:3,
         value:3
      },
      {
         source:2,
         target:4,
         value:5
      },
      {
         source:2,
         target:5,
         value:3
      },
      {
         source:2,
         target:6,
         value:12
      },
      {
         source:2,
         target:7,
         value:2
      },
      {
         source:2,
         target:8,
         value:2
      },
      {
         source:2,
         target:9,
         value:13
      },
      {
         source:2,
         target:10,
         value:4
      },
      {
         source:2,
         target:11,
         value:7
      },
      {
         source:2,
         target:12,
         value:32
      },
      {
         source:2,
         target:13,
         value:12
      },
      {
         source:2,
         target:14,
         value:19
      },
      {
         source:2,
         target:15,
         value:2
      },
      {
         source:2,
         target:16,
         value:8
      },
      {
         source:2,
         target:17,
         value:8
      },
      {
         source:2,
         target:18,
         value:11
      },
      {
         source:2,
         target:19,
         value:10
      },
      {
         source:2,
         target:20,
         value:3
      },
      {
         source:2,
         target:21,
         value:17
      },
      {
         source:2,
         target:22,
         value:11
      },
      {
         source:2,
         target:23,
         value:6
      },
      {
         source:2,
         target:24,
         value:22
      },
      {
         source:2,
         target:25,
         value:21
      },
      {
         source:2,
         target:26,
         value:3
      },
      {
         source:2,
         target:27,
         value:6
      },
      {
         source:2,
         target:28,
         value:12
      },
      {
         source:3,
         target:4,
         value:2
      },
      {
         source:3,
         target:5,
         value:20
      },
      {
         source:3,
         target:6,
         value:40
      },
      {
         source:3,
         target:7,
         value:18
      },
      {
         source:3,
         target:8,
         value:2
      },
      {
         source:3,
         target:9,
         value:4
      },
      {
         source:3,
         target:10,
         value:9
      },
      {
         source:3,
         target:11,
         value:8
      },
      {
         source:3,
         target:12,
         value:11
      },
      {
         source:3,
         target:13,
         value:6
      },
      {
         source:3,
         target:14,
         value:5
      },
      {
         source:3,
         target:15,
         value:2
      },
      {
         source:3,
         target:16,
         value:7
      },
      {
         source:3,
         target:17,
         value:8
      },
      {
         source:3,
         target:18,
         value:6
      },
      {
         source:3,
         target:19,
         value:7
      },
      {
         source:3,
         target:20,
         value:3
      },
      {
         source:3,
         target:21,
         value:6
      },
      {
         source:3,
         target:22,
         value:6
      },
      {
         source:3,
         target:23,
         value:18
      },
      {
         source:3,
         target:24,
         value:9
      },
      {
         source:3,
         target:25,
         value:15
      },
      {
         source:3,
         target:26,
         value:4
      },
      {
         source:3,
         target:27,
         value:4
      },
      {
         source:3,
         target:28,
         value:7
      },
      {
         source:4,
         target:16,
         value:7
      },
      {
         source:4,
         target:5,
         value:4
      },
      {
         source:4,
         target:6,
         value:9
      },
      {
         source:4,
         target:7,
         value:3
      },
      {
         source:4,
         target:8,
         value:18
      },
      {
         source:4,
         target:9,
         value:10
      },
      {
         source:4,
         target:10,
         value:3
      },
      {
         source:4,
         target:11,
         value:9
      },
      {
         source:4,
         target:12,
         value:13
      },
      {
         source:4,
         target:13,
         value:11
      },
      {
         source:4,
         target:14,
         value:7
      },
      {
         source:4,
         target:15,
         value:5
      },
      {
         source:4,
         target:17,
         value:1
      },
      {
         source:4,
         target:18,
         value:7
      },
      {
         source:4,
         target:19,
         value:7
      },
      {
         source:4,
         target:20,
         value:8
      },
      {
         source:4,
         target:21,
         value:15
      },
      {
         source:4,
         target:22,
         value:11
      },
      {
         source:4,
         target:23,
         value:9
      },
      {
         source:4,
         target:24,
         value:6
      },
      {
         source:4,
         target:25,
         value:19
      },
      {
         source:4,
         target:26,
         value:4
      },
      {
         source:4,
         target:27,
         value:13
      },
      {
         source:4,
         target:28,
         value:7
      },
      {
         source:5,
         target:16,
         value:8
      },
      {
         source:5,
         target:6,
         value:143
      },
      {
         source:5,
         target:7,
         value:43
      },
      {
         source:5,
         target:8,
         value:3
      },
      {
         source:5,
         target:9,
         value:13
      },
      {
         source:5,
         target:10,
         value:6
      },
      {
         source:5,
         target:11,
         value:8
      },
      {
         source:5,
         target:12,
         value:30
      },
      {
         source:5,
         target:13,
         value:8
      },
      {
         source:5,
         target:14,
         value:8
      },
      {
         source:5,
         target:15,
         value:4
      },
      {
         source:5,
         target:17,
         value:10
      },
      {
         source:5,
         target:18,
         value:13
      },
      {
         source:5,
         target:19,
         value:16
      },
      {
         source:5,
         target:20,
         value:4
      },
      {
         source:5,
         target:21,
         value:14
      },
      {
         source:5,
         target:22,
         value:7
      },
      {
         source:5,
         target:23,
         value:17
      },
      {
         source:5,
         target:24,
         value:13
      },
      {
         source:5,
         target:25,
         value:13
      },
      {
         source:5,
         target:26,
         value:14
      },
      {
         source:5,
         target:27,
         value:6
      },
      {
         source:5,
         target:28,
         value:8
      },
      {
         source:6,
         target:16,
         value:253
      },
      {
         source:6,
         target:7,
         value:76
      },
      {
         source:6,
         target:8,
         value:160
      },
      {
         source:6,
         target:9,
         value:36
      },
      {
         source:6,
         target:10,
         value:15
      },
      {
         source:6,
         target:11,
         value:38
      },
      {
         source:6,
         target:12,
         value:100
      },
      {
         source:6,
         target:13,
         value:53
      },
      {
         source:6,
         target:14,
         value:39
      },
      {
         source:6,
         target:15,
         value:67
      },
      {
         source:6,
         target:17,
         value:39
      },
      {
         source:6,
         target:18,
         value:114
      },
      {
         source:6,
         target:19,
         value:52
      },
      {
         source:6,
         target:20,
         value:109
      },
      {
         source:6,
         target:21,
         value:46
      },
      {
         source:6,
         target:22,
         value:29
      },
      {
         source:6,
         target:23,
         value:20
      },
      {
         source:6,
         target:24,
         value:38
      },
      {
         source:6,
         target:25,
         value:31
      },
      {
         source:6,
         target:26,
         value:62
      },
      {
         source:6,
         target:27,
         value:21
      },
      {
         source:6,
         target:28,
         value:252
      },
      {
         source:7,
         target:16,
         value:11
      },
      {
         source:7,
         target:22,
         value:8
      },
      {
         source:7,
         target:8,
         value:7
      },
      {
         source:7,
         target:9,
         value:11
      },
      {
         source:7,
         target:10,
         value:10
      },
      {
         source:7,
         target:11,
         value:13
      },
      {
         source:7,
         target:12,
         value:24
      },
      {
         source:7,
         target:13,
         value:9
      },
      {
         source:7,
         target:14,
         value:9
      },
      {
         source:7,
         target:15,
         value:4
      },
      {
         source:7,
         target:17,
         value:16
      },
      {
         source:7,
         target:18,
         value:16
      },
      {
         source:7,
         target:19,
         value:12
      },
      {
         source:7,
         target:20,
         value:7
      },
      {
         source:7,
         target:21,
         value:11
      },
      {
         source:7,
         target:23,
         value:23
      },
      {
         source:7,
         target:24,
         value:8
      },
      {
         source:7,
         target:25,
         value:23
      },
      {
         source:7,
         target:26,
         value:15
      },
      {
         source:7,
         target:27,
         value:8
      },
      {
         source:7,
         target:28,
         value:14
      },
      {
         source:8,
         target:16,
         value:31
      },
      {
         source:8,
         target:9,
         value:3
      },
      {
         source:8,
         target:10,
         value:3
      },
      {
         source:8,
         target:11,
         value:6
      },
      {
         source:8,
         target:12,
         value:14
      },
      {
         source:8,
         target:13,
         value:7
      },
      {
         source:8,
         target:14,
         value:3
      },
      {
         source:8,
         target:15,
         value:7
      },
      {
         source:8,
         target:17,
         value:7
      },
      {
         source:8,
         target:18,
         value:12
      },
      {
         source:8,
         target:19,
         value:4
      },
      {
         source:8,
         target:20,
         value:26
      },
      {
         source:8,
         target:21,
         value:5
      },
      {
         source:8,
         target:22,
         value:5
      },
      {
         source:8,
         target:23,
         value:6
      },
      {
         source:8,
         target:24,
         value:5
      },
      {
         source:8,
         target:25,
         value:12
      },
      {
         source:8,
         target:26,
         value:10
      },
      {
         source:8,
         target:27,
         value:6
      },
      {
         source:8,
         target:28,
         value:10
      },
      {
         source:9,
         target:16,
         value:12
      },
      {
         source:9,
         target:10,
         value:9
      },
      {
         source:9,
         target:11,
         value:19
      },
      {
         source:9,
         target:12,
         value:64
      },
      {
         source:9,
         target:13,
         value:29
      },
      {
         source:9,
         target:14,
         value:21
      },
      {
         source:9,
         target:15,
         value:5
      },
      {
         source:9,
         target:17,
         value:8
      },
      {
         source:9,
         target:18,
         value:24
      },
      {
         source:9,
         target:19,
         value:13
      },
      {
         source:9,
         target:20,
         value:8
      },
      {
         source:9,
         target:21,
         value:46
      },
      {
         source:9,
         target:22,
         value:18
      },
      {
         source:9,
         target:23,
         value:16
      },
      {
         source:9,
         target:24,
         value:35
      },
      {
         source:9,
         target:25,
         value:35
      },
      {
         source:9,
         target:26,
         value:3
      },
      {
         source:9,
         target:27,
         value:19
      },
      {
         source:9,
         target:28,
         value:26
      },
      {
         source:10,
         target:11,
         value:16
      },
      {
         source:10,
         target:12,
         value:14
      },
      {
         source:10,
         target:13,
         value:9
      },
      {
         source:10,
         target:14,
         value:5
      },
      {
         source:10,
         target:15,
         value:3
      },
      {
         source:10,
         target:16,
         value:3
      },
      {
         source:10,
         target:17,
         value:5
      },
      {
         source:10,
         target:18,
         value:8
      },
      {
         source:10,
         target:19,
         value:4
      },
      {
         source:10,
         target:20,
         value:2
      },
      {
         source:10,
         target:21,
         value:12
      },
      {
         source:10,
         target:22,
         value:6
      },
      {
         source:10,
         target:23,
         value:22
      },
      {
         source:10,
         target:24,
         value:11
      },
      {
         source:10,
         target:25,
         value:21
      },
      {
         source:10,
         target:26,
         value:7
      },
      {
         source:10,
         target:27,
         value:7
      },
      {
         source:10,
         target:28,
         value:8
      },
      {
         source:11,
         target:16,
         value:12
      },
      {
         source:11,
         target:12,
         value:34
      },
      {
         source:11,
         target:13,
         value:24
      },
      {
         source:11,
         target:14,
         value:15
      },
      {
         source:11,
         target:15,
         value:9
      },
      {
         source:11,
         target:17,
         value:10
      },
      {
         source:11,
         target:18,
         value:17
      },
      {
         source:11,
         target:19,
         value:13
      },
      {
         source:11,
         target:20,
         value:6
      },
      {
         source:11,
         target:21,
         value:32
      },
      {
         source:11,
         target:22,
         value:13
      },
      {
         source:11,
         target:23,
         value:26
      },
      {
         source:11,
         target:24,
         value:22
      },
      {
         source:11,
         target:25,
         value:32
      },
      {
         source:11,
         target:26,
         value:4
      },
      {
         source:11,
         target:27,
         value:18
      },
      {
         source:11,
         target:28,
         value:18
      },
      {
         source:12,
         target:16,
         value:24
      },
      {
         source:12,
         target:13,
         value:57
      },
      {
         source:12,
         target:14,
         value:78
      },
      {
         source:12,
         target:15,
         value:4
      },
      {
         source:12,
         target:17,
         value:17
      },
      {
         source:12,
         target:18,
         value:47
      },
      {
         source:12,
         target:19,
         value:45
      },
      {
         source:12,
         target:20,
         value:9
      },
      {
         source:12,
         target:21,
         value:86
      },
      {
         source:12,
         target:22,
         value:37
      },
      {
         source:12,
         target:23,
         value:26
      },
      {
         source:12,
         target:24,
         value:91
      },
      {
         source:12,
         target:25,
         value:101
      },
      {
         source:12,
         target:26,
         value:11
      },
      {
         source:12,
         target:27,
         value:34
      },
      {
         source:12,
         target:28,
         value:80
      },
      {
         source:13,
         target:16,
         value:15
      },
      {
         source:13,
         target:14,
         value:27
      },
      {
         source:13,
         target:15,
         value:9
      },
      {
         source:13,
         target:17,
         value:6
      },
      {
         source:13,
         target:18,
         value:35
      },
      {
         source:13,
         target:19,
         value:18
      },
      {
         source:13,
         target:20,
         value:8
      },
      {
         source:13,
         target:21,
         value:36
      },
      {
         source:13,
         target:22,
         value:11
      },
      {
         source:13,
         target:23,
         value:17
      },
      {
         source:13,
         target:24,
         value:32
      },
      {
         source:13,
         target:25,
         value:34
      },
      {
         source:13,
         target:26,
         value:6
      },
      {
         source:13,
         target:27,
         value:35
      },
      {
         source:13,
         target:28,
         value:26
      },
      {
         source:14,
         target:16,
         value:9
      },
      {
         source:14,
         target:15,
         value:4
      },
      {
         source:14,
         target:17,
         value:14
      },
      {
         source:14,
         target:18,
         value:16
      },
      {
         source:14,
         target:19,
         value:29
      },
      {
         source:14,
         target:20,
         value:4
      },
      {
         source:14,
         target:21,
         value:23
      },
      {
         source:14,
         target:22,
         value:13
      },
      {
         source:14,
         target:23,
         value:10
      },
      {
         source:14,
         target:24,
         value:34
      },
      {
         source:14,
         target:25,
         value:50
      },
      {
         source:14,
         target:26,
         value:3
      },
      {
         source:14,
         target:27,
         value:19
      },
      {
         source:14,
         target:28,
         value:40
      },
      {
         source:15,
         target:16,
         value:11
      },
      {
         source:15,
         target:17,
         value:1
      },
      {
         source:15,
         target:18,
         value:9
      },
      {
         source:15,
         target:19,
         value:9
      },
      {
         source:15,
         target:20,
         value:10
      },
      {
         source:15,
         target:21,
         value:6
      },
      {
         source:15,
         target:22,
         value:6
      },
      {
         source:15,
         target:23,
         value:11
      },
      {
         source:15,
         target:24,
         value:6
      },
      {
         source:15,
         target:25,
         value:6
      },
      {
         source:15,
         target:26,
         value:2
      },
      {
         source:15,
         target:27,
         value:6
      },
      {
         source:15,
         target:28,
         value:11
      },
      {
         source:16,
         target:17,
         value:5
      },
      {
         source:16,
         target:18,
         value:33
      },
      {
         source:16,
         target:19,
         value:5
      },
      {
         source:16,
         target:20,
         value:20
      },
      {
         source:16,
         target:21,
         value:14
      },
      {
         source:16,
         target:22,
         value:44
      },
      {
         source:16,
         target:23,
         value:7
      },
      {
         source:16,
         target:24,
         value:6
      },
      {
         source:16,
         target:25,
         value:13
      },
      {
         source:16,
         target:26,
         value:16
      },
      {
         source:16,
         target:27,
         value:3
      },
      {
         source:16,
         target:28,
         value:32
      },
      {
         source:17,
         target:18,
         value:10
      },
      {
         source:17,
         target:19,
         value:10
      },
      {
         source:17,
         target:20,
         value:8
      },
      {
         source:17,
         target:21,
         value:9
      },
      {
         source:17,
         target:22,
         value:5
      },
      {
         source:17,
         target:23,
         value:11
      },
      {
         source:17,
         target:24,
         value:16
      },
      {
         source:17,
         target:25,
         value:19
      },
      {
         source:17,
         target:26,
         value:10
      },
      {
         source:17,
         target:27,
         value:4
      },
      {
         source:17,
         target:28,
         value:17
      },
      {
         source:18,
         target:19,
         value:13
      },
      {
         source:18,
         target:20,
         value:10
      },
      {
         source:18,
         target:21,
         value:33
      },
      {
         source:18,
         target:22,
         value:21
      },
      {
         source:18,
         target:23,
         value:14
      },
      {
         source:18,
         target:24,
         value:20
      },
      {
         source:18,
         target:25,
         value:27
      },
      {
         source:18,
         target:26,
         value:17
      },
      {
         source:18,
         target:27,
         value:18
      },
      {
         source:18,
         target:28,
         value:26
      },
      {
         source:19,
         target:20,
         value:4
      },
      {
         source:19,
         target:21,
         value:17
      },
      {
         source:19,
         target:22,
         value:13
      },
      {
         source:19,
         target:23,
         value:8
      },
      {
         source:19,
         target:24,
         value:25
      },
      {
         source:19,
         target:25,
         value:34
      },
      {
         source:19,
         target:26,
         value:2
      },
      {
         source:19,
         target:27,
         value:19
      },
      {
         source:19,
         target:28,
         value:20
      },
      {
         source:20,
         target:21,
         value:7
      },
      {
         source:20,
         target:22,
         value:9
      },
      {
         source:20,
         target:23,
         value:4
      },
      {
         source:20,
         target:24,
         value:4
      },
      {
         source:20,
         target:25,
         value:8
      },
      {
         source:20,
         target:26,
         value:7
      },
      {
         source:20,
         target:27,
         value:5
      },
      {
         source:20,
         target:28,
         value:14
      },
      {
         source:21,
         target:22,
         value:24
      },
      {
         source:21,
         target:23,
         value:23
      },
      {
         source:21,
         target:24,
         value:38
      },
      {
         source:21,
         target:25,
         value:52
      },
      {
         source:21,
         target:26,
         value:10
      },
      {
         source:21,
         target:27,
         value:17
      },
      {
         source:21,
         target:28,
         value:27
      },
      {
         source:22,
         target:23,
         value:10
      },
      {
         source:22,
         target:24,
         value:13
      },
      {
         source:22,
         target:25,
         value:22
      },
      {
         source:22,
         target:26,
         value:6
      },
      {
         source:22,
         target:27,
         value:8
      },
      {
         source:22,
         target:28,
         value:15
      },
      {
         source:23,
         target:24,
         value:19
      },
      {
         source:23,
         target:25,
         value:36
      },
      {
         source:23,
         target:26,
         value:13
      },
      {
         source:23,
         target:27,
         value:15
      },
      {
         source:23,
         target:28,
         value:14
      },
      {
         source:24,
         target:25,
         value:47
      },
      {
         source:24,
         target:26,
         value:6
      },
      {
         source:24,
         target:27,
         value:20
      },
      {
         source:24,
         target:28,
         value:33
      },
      {
         source:25,
         target:26,
         value:14
      },
      {
         source:25,
         target:27,
         value:36
      },
      {
         source:25,
         target:28,
         value:54
      },
      {
         source:26,
         target:27,
         value:3
      },
      {
         source:26,
         target:28,
         value:12
      },
      {
         source:27,
         target:28,
         value:23
      }
   ],
   multigraph:false
}