---
engines:
  checkstyle:
    enabled: true
    channel: "beta"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- docs/
- sample/
- lib/deprecated/
- lib/slack/
- test/slack/
- test/data/
- ext/
- ubuntu.py
- slack.py
