DEBUGGER = True
LOG_DIRECTORY = "/home/rohan/parser_files/YearlyLogFiles/"
OUTPUT_DIRECTORY = "/home/rohan/Desktop/"
STARTING_DATE = "2013-1-1"
ENDING_DATE = "2013-1-31"

#change to ["ALL"] if want to perform analysis over all channels
# CHANNEL_NAME = ["#kubuntu-devel"]
CHANNEL_NAME = ["ALL"]

#increase if using channel_user_presence
# MAX_EXPECTED_DIFF_NICKS = 5000
MAX_EXPECTED_DIFF_NICKS = 100000 

#message_number_graph
THRESHOLD_MESSAGE_NUMBER_GRAPH = 10

#channel_user_presence
STARTING_HASH_CHANNEL = 1000000
FILTER_FOR_CHANNEL_USER_GRAPH = 25
FILTER_FOR_CHANNEL_CHANNEL_GRAPH = 0
FILTER_FOR_USER_USER_GRAPH = 0
CHANNEL_USER_MAX_DEG = 1000
FILTER_TOP_USERS = 100
FILTER_TOP_CHANNELS = 30
GENERATE_DEGREE_ANAL = False
PRINT_CHANNEL_USER_HASH = False